language: bash
addons:
  apt:
    packages:
services:
  - docker
script:
  - sudo make -j20 -f minisign.mk
  - sudo rm /bin/sh
  - sudo ln -s /bin/bash /bin/sh
  - sudo ldconfig
  - bash build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push panux/panux;
    fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a03b51747a5dac47ec4a
    on_success: always
    on_failure: always
    on_start: never
