language: bash
addons:
  apt:
    packages:
    - expect
    - lua5.2
services:
  - docker
script:
  - make -j2 -f minisign.mk
  - bash build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push panux/panux;
    fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a03b51747a5dac47ec4a
    on_success: always
    on_failure: always
    on_start: never
