language: bash
services:
  - docker
script:
  - bash build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push panux/panux;
    fi
